"""

Script file generated by Yourk, www.RIPSAW.com/Yourk/experiment_1

Instructions:
	- copy this code and paste it into a *.py file
	- open Rhino (rhino3d.com). The software is currently in development for Mac and free to use. Commercial license is needed for Windows. [stay tuned for a SketchUp implementation]
	- type RunPythonScript in the Rhino command line, and select your file.
	- in the current development phase, the geometry generated by this script needs to be trimmed manually to obtain the final 3d model. Stay tuned for full automation.
	- Rhino exports seamlessly into .stl format, which is directly imported into MakerWare, the software used to send geometries to MakerBot 3d printers. Check out the image gallery under RIPSAW.com/design/Yourk/ for images of the very first Yourk 3d printing process.

"""

import rhinoscriptsyntax as rs

import math

def Main():

	rs.AddPoint([-4.26,-6.95,0.00])
	rs.AddPoint([-10.53,23.06,0.00])
	rs.AddPoint([-22.41,9.85,0.00])
	rs.AddPoint([21.98,-25.00,0.00])
	rs.AddPoint([35.83,2.32,0.00])
	rs.AddLine([-10.53,10.71,0.00], [-22.41,22.20,0.00])
	rs.AddLine([-22.48,22.39,0.00], [-89.60,22.39,0.00])
	rs.AddLine([-10.45,10.51,0.00], [11.38,10.51,0.00])
	rs.AddLine([-21.68,-6.95,0.00], [-5.00,9.85,0.00])
	rs.AddLine([-4.94,10.06,0.00], [-4.94,10.59,0.00])
	rs.AddLine([-21.73,-7.16,0.00], [-21.73,-69.21,0.00])
	rs.AddLine([-10.53,5.11,0.00], [-4.26,11.00,0.00])
	rs.AddLine([-4.19,11.19,0.00], [11.26,11.19,0.00])
	rs.AddLine([35.83,-18.02,0.00], [21.98,-4.66,0.00])
	rs.AddLine([35.85,-18.27,0.00], [94.98,-18.27,0.00])
	rs.AddLine([21.95,-4.42,0.00], [-19.33,-4.42,0.00])
	rs.AddLine([0.04,-25.00,0.00], [17.67,-6.95,0.00])
	rs.AddLine([17.88,-6.89,0.00], [17.88,18.15,0.00])
	rs.AddLine([-0.17,-25.06,0.00], [-0.17,-82.59,0.00])
	rs.AddLine([20.34,-6.95,0.00], [11.22,2.32,0.00])
	rs.AddLine([11.15,2.51,0.00], [11.15,11.30,0.00])
	rs.AddLine([2.44,2.32,0.00], [22.86,23.06,0.00])
	rs.AddLine([23.02,23.17,0.00], [23.02,69.24,0.00])
	rs.AddLine([10.48,11.16,0.00], [10.48,11.42,0.00])
	rs.AddLine([17.21,17.21,0.00], [17.21,17.47,0.00])
	rs.AddLine([-21.48,-17.23,0.00], [-21.75,-17.23,0.00])
	rs.AddLine([2.95,-21.63,0.00], [2.95,-22.16,0.00])
	rs.AddLine([2.28,-22.29,0.00], [2.28,-22.83,0.00])
Main() 